[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[dependencies]
flexi_logger = "0.28.5"
log = "0.4"
crossbeam = "0.8.4"
lazy_static = "1.4"
tokio = { version = "1.38.0", features = ["full"] }
chrono = "0.4.38"
disk_log = "1.0.0"